config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users, only:[:index, :create, :show, :edit, :update]
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :current_user_check, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully"
    redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully"
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  # def current_user_check
  #   @book = Book.find(params[:id])
  #   if @book.user != current_user
  #     redirect_to books_path(@book.id)
  #   end
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :current_user_check, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully"
    redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    # binding.pry
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully"
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  # def current_user_check
  #   @user = User.find(params[:id])
  #   if @user != current_user
  #   redirect_to users_path
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <% book_errors = @book.errors.count %>
        <% if book_errors == 1 %>
        <%= @book.errors.count %> error prohibited this obj from being saved:
        <% else %>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
        <% end %>
        <p><% @book.errors.full_messages.each do |message| %></p>
        <%= message %>
        <% end %>
        <% end %>

        <%= form_with model:@book, local:true do |f| %>
        <div class= "form_group">
          <div class= "book_title">Title</div>
          <%= f.text_field :title %>
        </div>
        <div class= "form_group">
          <div class= "book_opinion">Opinion</div>
          <%= f.text_area :body %>
        </div>
        <div class= "form_group">
          <%= f.submit 'Update Book'%>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-3">
       <%= render 'layouts/userform', user:@user %>

       <%= render 'layouts/bookform', book:@book %>

      </div>
      <div class= "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class= "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan= "3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
              <%= link_to user_path(book.user.id) do %>
              <div><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></div>
              <% end %>
              </td>
              <td>
              <%= link_to book_path(book.id) do %>
              <div><%= book.title %></div>
              <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-3">
       <%= render 'layouts/userform', user:@user %>

       <%= render 'layouts/bookform', book:@book %>

      </div>
      <div class= "col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class= "table">
          <tbody>
            <tr>
              <td>
               <%= link_to user_path(@books.user.id) do %>
               <div><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></div>
               <div><%= @books.user.name %><div>
               <% end %>
              </td>
              <td><%= @books.title %></td>
              <td><%= @books.body %></td>
              <% if @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@books.id) %></td>
              <td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "本当に削除しますか？"%></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "px-3 mx-auto">
        <h1>Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !
        </h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!</h1>
        <p>in
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        </p>
        <p>you can share and exchange your opinions, inpressions, and emotions</p>
        <p>about various books!</p>
        <div class= "btn-wrapper col-10 mx-auto">
          <div class= "row">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-secondary btn-block" %>
          </div>
          <div class= "row">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-secondary btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_bookform.html.erb
<h2>New book</h2>
<% if book.errors.any? %> <!-- @bookからbookに変更 -->
<% book_errors = book.errors.count %> <!-- @bookからbookに変更 -->
<% if book_errors == 1 %>
<%= book.errors.count %> error prohibited this obj from being saved: <!-- @bookからbookに変更 -->
<% else %>
<%= book.errors.count %> errors prohibited this obj from being saved: <!-- @bookからbookに変更 -->
<% end %>
<p><% book.errors.full_messages.each do |message| %></p> <!-- @bookからbookに変更 -->
<%= message %>
<% end %>
<% end %>

<%= form_with model:book, local:true do |f| %> <!-- @bookからbookに変更 -->
<div class= "form_group">
  <div class= "book_title">Title</div> <!--labelからdivに変更-->
  <%= f.text_field :title %>
</div>
<div class= "form_group">
  <div class= "book_opinion">Opinion</div> <!--labelからdivに変更-->
  <%= f.text_area :body %>
</div>
<div class= "form_group">
  <%= f.submit 'Create Book'%>
</div>
<% end %>

app/views/layouts/_userform.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpeg', fallback: "no_image.jpg" %> <!-- @userをuserに変更-->
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th> <!-- @userをuserに変更-->
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th> <!-- @userをuserに変更-->
      </tr>
    </tbody>
  </table>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %> <!-- @userをuserに変更-->
    <i class="fas fa-user-cog"></i>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name= "viewport" content="width=device-width, initial-scale=1,maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class= "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class= "container">
          <a class= "navbar-brand" href= "/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class= "collapse navbar-collapse" id= "navbarNavDropdown">
            <ul class= "navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <i class="fas fa-home"></i>
                <%= link_to "Home", user_path(current_user.id) %>
              </li>
              <li>
                <i class="fas fa-users"></i>
                <%= link_to "Users", users_path %>
              </li>
              <li>
                <i class="fas fa-book-open"></i>
                <%= link_to "Books", books_path %>
              </li>
              <li>
                <i class="fas fa-sign-out-alt"></i>
                <%= link_to "logout", destroy_user_session_path, method: :delete %>
              </li>
              <% else %>
              <li>
                <i class="fas fa-home"></i>
                <%= link_to "Home", root_path %>
              </li>
              <li>
                <i class="fas fa-link"></i>
                <%= link_to "About", home_about_path %>
              </li>
              <li>
                <i class="fas fa-user-plus"></i>
                <%= link_to "sign up", new_user_registration_path %>
              </li>
              <li>
                <i class="fas fa-sign-in-alt"></i>
                <%= link_to "login", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
      <div class= "flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <main>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h2>User info</h2>
       <% if @user.errors.any? %>
       <% user_errors = @user.errors.count %>
       <% if user_errors == 1 %>
       <%= @user.errors.count %> error prohibited this obj from being saved:
       <% else %>
       <%= @user.errors.count %> errors prohibited this obj from being saved:
       <% end %>
       <p><% @user.errors.full_messages.each do |message|%></p>
       <%= message %>
       <% end %>
       <% end %>

       <%= form_with model:@user, local:true do |f| %>
       <div class= "form_group">
         <div class= "user_name">Name</div>
         <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %>
       </div>
       <div class= "form_group">
         <div class= "user_image">Image</div>
         <%= f.attachment_field :profile_image, placeholder:"Image" %>
       </div>
       <div class= "form_group">
         <div class= "user_introduction">Introduction</div>
         <%= f.text_area :introduction, autofocus: true %>
       </div>
       <div class= "form_group">
        <%= f.submit "Update User" %>
       </div>
       <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-3">
       <%= render 'layouts/userform', user:@user %>

       <%= render 'layouts/bookform', book:@book %>

      </div>
      <div class= "col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class= "table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan= "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-3">
       <%= render 'layouts/userform', user:@user %>

       <%= render 'layouts/bookform', book:@book %>

      </div>
      <div class= "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class= "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan= "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                <div><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></div>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <div><%= book.title %></div>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>
<%= paginate @books %>